"""
Chaos point + audio-reactive cymatic, single-pass shader, with regen-driven
sliders for light/scale/frequency control on /project1/feedback_viz.

The chaos uniforms (uChaosX, uChaosY, etc.) stay OSC-bound for audio reactivity.
Slider values bake into the shader text via a Python regen function called on
slider change. No uniform-binding needed for the sliders.

Run in TD textport:
    p=r'\\\\wsl.localhost\\Ubuntu\\home\\sphinxy\\Feedback\\td\\build_chaos_with_cymatic.py'
    exec(open(p).read())
"""

CHAOS_VIZ_PATH = '/project1/feedback_viz/chaos_viz'
PARENT_PATH = '/project1/feedback_viz'
RENDER_DAT_NAME = 'chaos_render'
PAREXEC_DAT_NAME = 'chaos_paramexec'


CHAOS_TEMPLATE = '''// Chaos Attractor Point + Audio-Reactive Cymatic Background
// Shader text regenerated by chaos_render.render() on slider change.

uniform float uChaosX;
uniform float uChaosY;
uniform float uChaosZ;
uniform float uAmp;
uniform float uAttractor;
uniform float uChaosGain;
uniform float uDecay;
uniform float uDrive;

out vec4 fragColor;

#define PI 3.14159265359

float chladni(vec2 p, float n, float m, float pn, float pm) {
    return sin(n * PI * p.x + pn) * sin(m * PI * p.y + pm)
         + sin(m * PI * p.x + pm) * sin(n * PI * p.y + pn);
}

float hash21(vec2 p) {
    p = fract(p * vec2(123.34, 456.21));
    p += dot(p, p + 45.32);
    return fract(p.x * p.y);
}

void main()
{
    vec2 uv = vUV.st;
    vec2 res = uTDOutputInfo.res.zw;
    float aspect = res.x / res.y;

    // Slider-baked constants (regenerated on /project1/feedback_viz slider change)
    float pointBright   = __Pointbright__;
    float pointVisible  = __Pointvisible__;
    float cymBright     = __Cymbright__;
    float cymScale      = __Cymscale__;
    float cymFreqN      = __Cymfreqn__;
    float cymFreqM      = __Cymfreqm__;
    float cymAudioDepth = __Cymaudiodepth__;
    float cymWarp       = __Cymwarp__;
    float cymPhase      = __Cymphase__;
    float cymContrast   = __Cymcontrast__;

    // ============================================================
    // CYMATIC BACKGROUND (continuous audio warp)
    // ============================================================

    vec2 plate = (uv - 0.5) * 2.0;
    plate.x *= aspect;

    // SMOOTH AUDIO TRANSFORMS — fixed cymatic structure breathes/morphs.
    // Mode numbers stay constant (no slideshow). Audio warps, scales,
    // rotates, phase-shifts the SAME underlying standing-wave figure.

    // Domain warp: translates the pattern with chaos motion
    vec2 audioOffset = vec2(uChaosX, uChaosY) * cymWarp * 0.6;
    plate += audioOffset;

    // Scale: expand/contract pulse with amplitude (breath)
    float audioScale = 1.0 + uAmp * 0.4 * cymAudioDepth + uChaosGain * 0.3;
    plate *= audioScale;

    // Rotate: smooth swirl driven by Z
    float audioRot = uChaosZ * cymAudioDepth * 0.3;
    float cs = cos(audioRot), sn = sin(audioRot);
    plate = mat2(cs, -sn, sn, cs) * plate;

    // Phase modulation continues to slide the standing wave fronts
    float phaseN = uChaosZ * cymPhase * 8.0 + uAmp * cymAudioDepth * 2.0;
    float phaseM = -uChaosZ * cymPhase * 6.0 + uDrive * cymAudioDepth * 1.5;

    // Mode numbers are FIXED — preserves the cymatic structure so transforms
    // morph it instead of jumping to a different pattern.
    float modeN = cymFreqN;
    float modeM = cymFreqM;

    float c1 = chladni(plate * 0.5, modeN, modeM, phaseN, phaseM);
    float c2 = chladni(plate * 0.5, modeN + 1.7, modeM + 1.3, phaseN + 0.7, phaseM + 0.5);
    float cymatic = mix(c1, c2, 0.5 + 0.4 * sin(phaseN));

    float fieldNorm = cymatic / (0.5 + abs(cymatic) * 0.5);

    float lineWidthUV = (0.006 + uChaosGain * 0.02) * cymScale;
    float dist = abs(fieldNorm);

    float fw = max(fwidth(dist), 0.001);
    float lineCore = smoothstep(lineWidthUV + fw, lineWidthUV * 0.4, dist);
    float haloWidth = lineWidthUV * 4.5;
    float halo = smoothstep(haloWidth, lineWidthUV * 0.6, dist);
    halo = halo * halo * 0.4;

    float jitter = (hash21(uv * 1200.0) - 0.5) * lineWidthUV * 0.3;
    float jitteredCore = smoothstep(lineWidthUV * 1.2, lineWidthUV * 0.4, dist + jitter);
    lineCore = max(lineCore, jitteredCore * 0.8);

    float nodalLine = clamp(lineCore + halo, 0.0, 1.0);
    // Brightness pulses with amplitude — Audio Depth slider amplifies the pulse
    nodalLine *= cymBright * (0.3 + uAmp * 1.5 * cymAudioDepth) * (0.5 + uChaosGain * 0.7);
    nodalLine = pow(nodalLine, max(cymContrast, 0.4));

    vec3 cymaticColor = mix(vec3(0.85, 0.9, 1.0),
                            vec3(1.0, 0.85, 0.6),
                            clamp(uDecay / 1.5, 0.0, 1.0) * 0.6);
    vec3 cymaticContribution = cymaticColor * nodalLine;

    // ============================================================
    // CHAOS POINT (toggleable, brightness-controlled)
    // ============================================================

    vec3 pointColor = vec3(0.0);

    if (pointVisible > 0.5) {
        float scale = 0.025;
        int att = int(uAttractor);
        if (att == 0) scale = 0.022;
        else if (att == 1) scale = 0.035;
        else if (att == 2) scale = 0.15;
        else if (att == 3) scale = 0.04;
        else if (att == 4) scale = 0.25;

        vec2 attPos = vec2(uChaosX * scale, uChaosY * scale + uChaosZ * scale * 0.15);
        attPos.x /= aspect;
        attPos = attPos * 0.5 + 0.5;

        vec2 fragPos = uv;
        fragPos.x *= aspect;
        vec2 aPos = attPos;
        aPos.x *= aspect;
        float pdist = length(fragPos - aPos);

        float baseSize = 0.003 + uDrive * 0.004;
        float pointSize = baseSize + uAmp * 0.008;
        float pIntensity = exp(-pdist * pdist / (pointSize * pointSize * 2.0));
        float pBrightness = 0.3 + uAmp * 0.7;

        float haloSize = pointSize * 4.0;
        float pHalo = exp(-pdist * pdist / (haloSize * haloSize * 2.0)) * 0.15;
        float chaosGlow = uChaosGain * 0.1;

        float pTotal = (pIntensity * pBrightness + pHalo + chaosGlow * pIntensity) * pointBright;
        pointColor = vec3(pTotal);

        float warmth = clamp(uDecay / 1.5, 0.0, 1.0) * 0.08;
        pointColor.r += warmth * pTotal;
        pointColor.b -= warmth * pTotal * 0.5;
    }

    // ============================================================
    // COMPOSITE
    // ============================================================

    vec3 finalColor = clamp(cymaticContribution + pointColor, 0.0, 1.0);
    fragColor = TDOutputSwizzle(vec4(finalColor, 1.0));
}
'''


RENDER_DAT_PY = '''# Renders chaos+cymatic shader from /project1/feedback_viz Chaos page params.

PARAM_NAMES = [
    'Pointbright', 'Pointvisible',
    'Cymbright', 'Cymscale', 'Cymfreqn', 'Cymfreqm',
    'Cymaudiodepth', 'Cymwarp', 'Cymphase', 'Cymcontrast',
]

def render():
    fv = op('/project1/feedback_viz')
    template_dat = op('/project1/feedback_viz/chaos_template')
    out_dat = op('/project1/feedback_viz/chaos_glsl_src')
    if fv is None or template_dat is None or out_dat is None:
        return
    template = template_dat.text
    for name in PARAM_NAMES:
        try:
            v = float(fv.par[name].eval())
        except Exception:
            v = 0.0
        template = template.replace(f"__{name}__", f"{v:.6f}")
    out_dat.text = template
'''


PAREXEC_DAT_PY = '''# Watches /project1/feedback_viz Chaos page params, regenerates shader on change.

def onValueChange(par, prev):
    op('/project1/feedback_viz/chaos_render').module.render()
    return

def onPulse(par): return
def onExpressionChange(par, val, prev):
    op('/project1/feedback_viz/chaos_render').module.render()
    return
def onExportChange(par, val, prev): return
def onEnableChange(par, val, prev): return
def onModeChange(par, prev): return
'''


CUSTOM_PARAMS = [
    # (name, label, default, min, max)
    ('Pointbright',   'Point Brightness',   0.6,  0.0, 3.0),
    ('Pointvisible',  'Point Visible (0/1)', 1.0, 0.0, 1.0),
    ('Cymbright',     'Cymatic Brightness', 0.7,  0.0, 3.0),
    ('Cymscale',      'Cymatic Line Scale', 1.0,  0.2, 4.0),
    ('Cymfreqn',      'Cymatic Freq N',     2.0,  1.0, 12.0),
    ('Cymfreqm',      'Cymatic Freq M',     3.0,  1.0, 12.0),
    ('Cymaudiodepth', 'Cymatic Audio Depth', 2.0, 0.0, 6.0),
    ('Cymwarp',       'Cymatic Warp',       1.5,  0.0, 5.0),
    ('Cymphase',      'Cymatic Phase Gain', 1.5,  0.0, 5.0),
    ('Cymcontrast',   'Cymatic Contrast',   1.0,  0.3, 4.0),
]


def main():
    print("=" * 60)
    print("Chaos + Cymatic with regen-driven sliders")
    print("=" * 60)

    glsl = op(CHAOS_VIZ_PATH)
    if glsl is None:
        print(f"[ERROR] {CHAOS_VIZ_PATH} not found")
        return
    parent = op(PARENT_PATH)

    # 1. Write template DAT
    tmpl = parent.op('chaos_template')
    if tmpl is None:
        tmpl = parent.create('textDAT', 'chaos_template')
        tmpl.nodeX = glsl.nodeX - 500
        tmpl.nodeY = glsl.nodeY - 100
    tmpl.text = CHAOS_TEMPLATE
    print(f"[OK] Template DAT: {tmpl.path}")

    # 2. Output shader DAT
    out_dat = parent.op('chaos_glsl_src')
    if out_dat is None:
        out_dat = parent.create('textDAT', 'chaos_glsl_src')
        out_dat.nodeX = glsl.nodeX - 250
        out_dat.nodeY = glsl.nodeY - 100
    print(f"[OK] Output shader DAT: {out_dat.path}")

    # 3. Render module
    render_dat = parent.op(RENDER_DAT_NAME)
    if render_dat is None:
        render_dat = parent.create('textDAT', RENDER_DAT_NAME)
        render_dat.nodeX = glsl.nodeX - 500
        render_dat.nodeY = glsl.nodeY - 200
    render_dat.text = RENDER_DAT_PY
    print(f"[OK] Render module: {render_dat.path}")

    # 4. Custom params on feedback_viz (add 'Chaos' page if not present)
    page = None
    for pg in parent.customPages:
        if pg.name == 'Chaos':
            pg.destroy()
            break
    page = parent.appendCustomPage('Chaos')
    for name, label, default, lo, hi in CUSTOM_PARAMS:
        page.appendFloat(name, label=label)
        p = parent.par[name]
        p.default = default
        p.min = lo
        p.max = hi
        p.normMin = lo
        p.normMax = hi
        p.clampMin = True
        p.clampMax = True
        p.val = default
    print(f"[OK] Added 'Chaos' page with {len(CUSTOM_PARAMS)} sliders to {parent.path}")

    # 5. ParExecute DAT
    pex = parent.op(PAREXEC_DAT_NAME)
    if pex is None:
        pex = parent.create('parameterexecuteDAT', PAREXEC_DAT_NAME)
        pex.nodeX = glsl.nodeX - 500
        pex.nodeY = glsl.nodeY - 300
    pex.text = PAREXEC_DAT_PY
    pex.par.op = parent.path
    pex.par.pars = ' '.join(n for n, *_ in CUSTOM_PARAMS)
    pex.par.valuechange = True
    pex.par.active = True
    print(f"[OK] ParExec watcher: {pex.path}")

    # 6. Initial render
    try:
        render_dat.module.render()
        print(f"[OK] Initial shader render filled {out_dat.path}")
    except Exception as e:
        print(f"[WARN] Initial render failed: {e}")

    # 7. Wire shader DAT to GLSL TOP
    glsl.par.pixeldat = out_dat.path

    print()
    print("=" * 60)
    print("Done. Click /project1/feedback_viz, find the 'Chaos' page in the")
    print("parameter pane. Drag sliders. Shader regenerates on each change.")
    print()
    print("Useful first moves:")
    print("  - Point Brightness: 0.4 (dimmer dot) or 0 (off)")
    print("  - Point Visible: 0 to hide the dot entirely")
    print("  - Cymatic Audio Depth: 4-6 for stronger audio response")
    print("  - Cymatic Warp: 3-5 for visible domain morphing")
    print("=" * 60)


main()
